In [119]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

In [120]:
x_data = open("x_train", "r")
x_content = x_data.readlines()
x_data.close()

Making data usable:

In [121]:
x_list = []

for line in x_content:
    new_line = []
    for value in line.split():
        new_line.append(float(value))
    x_list.append(new_line)

In [122]:
x_list=np.array(x_list)
x_list

array([[8.00e-02, 8.00e-02, 1.68e+00, 1.98e+02, 1.98e+02],
       [8.00e-02, 8.00e-02, 1.69e+00, 1.98e+02, 1.98e+02],
       [8.00e-02, 8.00e-02, 1.70e+00, 1.98e+02, 1.98e+02],
       ...,
       [1.20e-01, 1.20e-01, 1.70e+00, 2.02e+02, 2.02e+02],
       [1.20e-01, 1.20e-01, 1.71e+00, 2.02e+02, 2.02e+02],
       [1.20e-01, 1.20e-01, 1.72e+00, 2.02e+02, 2.02e+02]])

In [123]:
x_train = pd.DataFrame(
    x_list,
    columns=["albi", "albv", "gtd", "tstrat", "tautot"]) #don't need to do this...

In [124]:
x_train

albi  albv   gtd  tstrat  tautot
0     0.08  0.08  1.68   198.0   198.0
1     0.08  0.08  1.69   198.0   198.0
2     0.08  0.08  1.70   198.0   198.0
3     0.08  0.08  1.71   198.0   198.0
4     0.08  0.08  1.72   198.0   198.0
...    ...   ...   ...     ...     ...
3120  0.12  0.12  1.68   202.0   202.0
3121  0.12  0.12  1.69   202.0   202.0
3122  0.12  0.12  1.70   202.0   202.0
3123  0.12  0.12  1.71   202.0   202.0
3124  0.12  0.12  1.72   202.0   202.0

[3125 rows x 5 columns]

In [125]:
Y_data = open("Y_train", "r")
Y_content = Y_data.readlines()
Y_data.close()

In [126]:
Y_list = []

for line in Y_content:
    new_line = []
    for value in line.split():
        new_line.append(float(value))
    Y_list.append(new_line)

In [127]:
Y_list=np.array(Y_list)
Y_list=np.array(Y_list)
Y_list

array([[ 2.00000e-06,  9.09846e+01,  8.35616e+01, ..., -2.20044e+01,
         5.25100e+01,  2.00000e+02],
       [ 2.00000e-06,  9.12543e+01,  8.35683e+01, ..., -2.20586e+01,
         5.28273e+01,  2.00000e+02],
       [ 2.00000e-06,  9.15236e+01,  8.35749e+01, ..., -2.21123e+01,
         5.31440e+01,  2.00000e+02],
       ...,
       [ 2.00000e-06,  1.01840e+02,  8.56081e+01, ..., -2.15498e+01,
         5.72009e+01,  2.00000e+02],
       [ 2.00000e-06,  1.02058e+02,  8.56110e+01, ..., -2.15983e+01,
         5.75336e+01,  2.00000e+02],
       [ 2.00000e-06,  1.02276e+02,  8.56139e+01, ..., -2.16464e+01,
         5.78658e+01,  2.00000e+02]])

Now the input and output data is conveniently in numpy arrays

In [128]:
overall_list = np.concatenate((x_list, Y_list), axis=1)
overall_list = np.array(overall_list)
overall_list.shape

(3125, 365)

The data should be standardized so error scores would make sense and different algorithms can be compared:

In [129]:
central_x = x_list[1562] #central x_point
central_Y = Y_list[1562] #central y_point

In [130]:
x_std_list = []
for i in range(len(x_list.T)):
    x_std_list.append(np.std(x_list[:,i]))
#x_std_list #gets standard deviation for each input parameter

In [131]:
Y_std_list = []
for i in range(len(Y_list.T)):
    Y_std_list.append(np.std(Y_list[:,i]))
#Y_std_list #gets standard deviation for each output parameter

In [132]:
x_stand = (x_list-central_x)/np.array(x_std_list)
Y_stand = (Y_list-central_Y)/np.array(Y_std_list) 
Y_stand[np.isnan(Y_stand)] = 0 #standardizes data

C:\Users\andre\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


In [133]:
x_stand

array([[-1.41421356, -1.41421356, -1.41421356, -1.41421356, -1.41421356],
       [-1.41421356, -1.41421356, -0.70710678, -1.41421356, -1.41421356],
       [-1.41421356, -1.41421356,  0.        , -1.41421356, -1.41421356],
       ...,
       [ 1.41421356,  1.41421356,  0.        ,  1.41421356,  1.41421356],
       [ 1.41421356,  1.41421356,  0.70710678,  1.41421356,  1.41421356],
       [ 1.41421356,  1.41421356,  1.41421356,  1.41421356,  1.41421356]])

In [73]:
Y_stand

array([[ 0.        , -1.54775812, -0.83713479, ..., -0.47745007,
        -1.94099266,  0.        ],
       [ 0.        , -1.47415022, -0.83172976, ..., -0.59496957,
        -1.71289008,  0.        ],
       [ 0.        , -1.4006515 , -0.8264054 , ..., -0.71140494,
        -1.48521883,  0.        ],
       ...,
       [ 0.        ,  1.41495277,  0.81382054, ...,  0.50823931,
         1.43123048,  0.        ],
       [ 0.        ,  1.47445044,  0.81616004, ...,  0.40307887,
         1.67040391,  0.        ],
       [ 0.        ,  1.53394811,  0.81849953, ...,  0.29878574,
         1.90921789,  0.        ]])

In [79]:
adjusted_overall = np.concatenate((x_stand, Y_stand), axis=1)
adjusted_overall = np.array(adjusted_overall) #final standardized set

Now get training and test sets:

In [80]:
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(adjusted_overall, test_size=0.2, random_state=42)

In [82]:
test_set.shape

(625, 365)

In [110]:
train_input = train_set[:,:5] #trainng input
train_output = train_set[:,5:] #training output
test_input = test_set[:,:5] #training input
test_output = test_set[:,5:] #training output


print(train_input.shape)#training input
print(train_output.shape)# training ouput
train_input

(2500, 5)
(2500, 360)


array([[-0.70710678, -1.41421356,  0.        , -1.41421356,  0.        ],
       [ 0.70710678,  1.41421356, -1.41421356,  1.41421356,  1.41421356],
       [ 0.70710678,  0.70710678,  1.41421356, -1.41421356,  0.70710678],
       ...,
       [-0.70710678,  1.41421356, -1.41421356, -1.41421356, -0.70710678],
       [ 0.        , -1.41421356,  1.41421356, -0.70710678,  0.70710678],
       [-0.70710678, -0.70710678, -1.41421356,  1.41421356,  0.        ]])

In [96]:
#try linear regression:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(train_input, train_output)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [97]:
from sklearn.metrics import mean_squared_error

train_predict = lin_reg.predict(train_input)
lin_mse = mean_squared_error(train_output, train_predict)
lin_rmse = np.sqrt(lin_mse)
lin_rmse 

0.09178811627799546

In [102]:
from sklearn.tree import DecisionTreeRegressor #now try some other ML algorithm

tree_reg = DecisionTreeRegressor(random_state=42)
tree_reg.fit(train_input, train_output)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=42, splitter='best')

In [103]:
train_predict = tree_reg.predict(train_input)
lin_mse = mean_squared_error(train_output, train_predict)
lin_rmse = np.sqrt(lin_mse)
lin_rmse #overfit?

0.0

In [104]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(tree_reg, train_input, train_output,
                         scoring="neg_mean_squared_error", cv=10)
tree_rmse_scores = np.sqrt(-scores)

In [105]:
lin_scores = cross_val_score(lin_reg, train_input, train_output,
                             scoring="neg_mean_squared_error", cv=10)
lin_rmse_scores = np.sqrt(-lin_scores)


In [106]:
def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard deviation:", scores.std())



In [107]:
display_scores(tree_rmse_scores)

Scores: [0.14869552 0.1455808  0.14408417 0.14678681 0.14138032 0.14962443
 0.14356079 0.13942225 0.14042499 0.1465968 ]
Mean: 0.14461568905968222
Standard deviation: 0.0032817560941252218


In [108]:
display_scores(lin_rmse_scores) #comparable errors...

Scores: [0.08830606 0.09392711 0.0914475  0.09485973 0.09582984 0.09308254
 0.09210176 0.08669882 0.08988807 0.09345168]
Mean: 0.09195931136349891
Standard deviation: 0.0027630731812358757


Trying decision tree and linear regression on test set:

In [111]:
test_predict = tree_reg.predict(test_input) #tree
lin_mse = mean_squared_error(test_output, test_predict)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

0.136729501916013

In [112]:
test_predict = lin_reg.predict(test_input) #linear regression
lin_mse = mean_squared_error(test_output, test_predict)
lin_rmse = np.sqrt(lin_mse)
lin_rmse #not bad!

0.0923414554994554